export type Application = {
  id: string;
  user_id?: string | null;
  company: string;
  role: string;
  job_url?: string | null;
  job_location?: string | null;
  job_deadline?: string | null;
  job_requirements?: string | null;
  job_responsibilities?: string | null;
  job_skills?: string | null;
  job_benefits?: string | null;
  application_instructions?: string | null;
  analysis_status?: string | null;
  analyzed_at?: string | null;
  status: string;
  date_applied?: string | null;
  notes?: string | null;
  persona_id?: string | null;
  raw_job_text?: string | null;
  source_type?: string | null;
  imported_at?: string | null;
  created_at?: string | null;
};
